title: Dat Huynh
url: "hbdat.github.io"
baseurl: ""

description: Efficient Machine Learning

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

remote_theme: ankitsultana/researcher@gem

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/index"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=A02E__AAAAAJ&hl=en&oi=ao"
 - name: "Github"
   link: "https://github.com/hbdat"


# Development Settings
port: 4000
host: 127.0.0.1
safe: false