title: Dat Huynh
url: "hbdat.github.io"
baseurl: ""

description: Can we trust machine decision?

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

remote_theme: ankitsultana/researcher@gem

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/index"
 - name: "Publication"
   link: "/publication"
 - name: "Github"
   link: "https://github.com/hbdat"


# Development Settings
port: 4000
host: 127.0.0.1
safe: false